name: Build and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: "3.10"
        miniforge-version: latest
        use-mamba: true
        mamba-version: "*"

    - name: Install ROOT
      run: |
        mamba create -c conda-forge --name conda_root_env root
        conda activate conda_root_env

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libopenblas-dev liblapack-dev libarmadillo-dev

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build
  
    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build

#    - name: Test
#      working-directory: ${{github.workspace}}/build
#      run: <test here>
