name: Build and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: rootproject/root:latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Get sudo
      run: |
        apt-get update
        apt-get install -y sudo
    
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: git doxygen libopenblas-dev liblapack-dev
        version: 1.0

    - name: Install Armadillo
      run: |
        mkdir -p external
        cd external
        wget https://sourceforge.net/projects/arma/files/armadillo-12.4.0.tar.xz
        tar -xf armadillo-12.4.0.tar.xz
        cd armadillo-12.4.0
        cmake .
        make install

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      run: |
        cd ${{github.workspace}}/build
        ctest
