name: Build and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: rootproject/root:latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y libopenblas-dev liblapack-dev libarmadillo-dev

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build
  
    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build

#    - name: Test
#      working-directory: ${{github.workspace}}/build
#      run: <test here>
