name: Build and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: rootproject/root:latest
    steps:
    - uses: actions/checkout@v3

    - name: Cache dependencies
      uses: actions/cache@v1.2.1
      with:
        path: /var/lib/apt/lists
        key: ${{runner.os}}-apt-${{hashFiles('**/apt-get.txt')}}
      id: cache_deps

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y git doxygen libopenblas-dev liblapack-dev
      env:
        APTGET: ${{steps.cache_deps.outputs.cache-hit}}

    - name: Cache Armadillo
      uses: actions/cache@v1.2.1
      with:
        path: external/armadillo-12.4.0
        key: ${{runner.os}}-armadillo-${{hashFiles('external/armadillo-12.4.0.tar.xz')}}
      id: cache_armadillo

    - name: Install Armadillo
      run: |
        mkdir -p external
        cd external
        if [ "${{ steps.cache_armadillo.outputs.cache-hit }}" != "true" ]; then
          wget https://sourceforge.net/projects/arma/files/armadillo-12.4.0.tar.xz
          tar -xf armadillo-12.4.0.tar.xz
          cd armadillo-12.4.0
          cmake .
          make install
        else
          echo "Using cached Armadillo"
        fi

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      run: |
        cd ${{github.workspace}}/build
        ctest
